// HISTORY
export const FETCH_HISTORY = 'FETCH_HISTORY'
export const FETCH_HISTORY_SUCCESS = 'FETCH_HISTORY_SUCCESS'
export const FETCH_HISTORY_FAILURE = 'FETCH_HISTORY_FAILURE'

// ROCKETS
export const FETCH_ROCKETS = 'FETCH_ROCKETS'
export const FETCH_ROCKETS_SUCCESS = 'FETCH_ROCKETS_SUCCESS'
export const FETCH_ROCKETS_FAILURE = 'FETCH_ROCKETS_FAILURE'

// LAUNCHES
export const FETCH_LAUNCHES = 'FETCH_LAUNCHES'
export const FETCH_LAUNCHES_SUCCESS = 'FETCH_LAUNCHES_SUCCESS'
export const FETCH_LAUNCHES_FAILURE = 'FETCH_LAUNCHES_FAILURE'

// LAUNCH
export const FETCH_LAUNCH = 'FETCH_LAUNCH'
export const FETCH_LAUNCH_SUCCESS = 'FETCH_LAUNCH_SUCCESS'
export const FETCH_LAUNCH_FAILURE = 'FETCH_LAUNCH_FAILURE'

export const POST_LAUNCH_DATA = 'POST_LAUNCH_DATA'
export const POST_LAUNCH_DATA_SUCCESS = 'POST_LAUNCH_DATA_SUCCESS'
export const POST_LAUNCH_DATA_FAILURE = 'POST_LAUNCH_DATA_FAILURE'